### PR TITLE
chore: bump libcryptsetup to 0.5.1

### PR DESCRIPTION
**Pull request by nullr0ute**
There's a build issue with newer versions of cryptsetup that needs a bugfix rust crate so bump from 0.5.0 to 0.5.1 to fix builds.

Signed-off-by: Peter Robinson <pbrobinson@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
is the build issue related to https://github.com/stratis-storage/project/issues/487?

**Comment by nullr0ute** [comment]
Don't think so, this is the failure with 0.5.0 that works with 0.5.1:

````
error[E0425]: cannot find value `CRYPT_ACTIVATE_READONLY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:15:39
   |
15 |     Readonly => libcryptsetup_rs_sys::CRYPT_ACTIVATE_READONLY,
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_NO_UUID` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:16:37
   |
16 |     NoUuid => libcryptsetup_rs_sys::CRYPT_ACTIVATE_NO_UUID,
   |                                     ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_SHARED` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:17:37
   |
17 |     Shared => libcryptsetup_rs_sys::CRYPT_ACTIVATE_SHARED,
   |                                     ^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_ALLOW_DISCARDS` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:18:44
   |
18 |     AllowDiscards => libcryptsetup_rs_sys::CRYPT_ACTIVATE_ALLOW_DISCARDS,
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_PRIVATE` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:19:38
   |
19 |     Private => libcryptsetup_rs_sys::CRYPT_ACTIVATE_PRIVATE,
   |                                      ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_CORRUPTED` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:20:40
   |
20 |     Corrupted => libcryptsetup_rs_sys::CRYPT_ACTIVATE_CORRUPTED,
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_SAME_CPU_CRYPT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:21:43
   |
21 |     SameCpuCrypt => libcryptsetup_rs_sys::CRYPT_ACTIVATE_SAME_CPU_CRYPT,
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_SUBMIT_FROM_CRYPT_CPUS` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:22:50
   |
22 |     SubmitFromCryptCpus => libcryptsetup_rs_sys::CRYPT_ACTIVATE_SUBMIT_FROM_CRYPT_CPUS,
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_IGNORE_CORRUPTION` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:23:47
   |
23 |     IgnoreCorruption => libcryptsetup_rs_sys::CRYPT_ACTIVATE_IGNORE_CORRUPTION,
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_RESTART_ON_CORRUPTION` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:24:50
   |
24 |     RestartOnCorruption => libcryptsetup_rs_sys::CRYPT_ACTIVATE_RESTART_ON_CORRUPTION,
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_IGNORE_ZERO_BLOCKS` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:25:47
   |
25 |     IgnoreZeroBlocks => libcryptsetup_rs_sys::CRYPT_ACTIVATE_IGNORE_ZERO_BLOCKS,
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_KEYRING_KEY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:26:41
   |
26 |     KeyringKey => libcryptsetup_rs_sys::CRYPT_ACTIVATE_KEYRING_KEY,
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_NO_JOURNAL` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:27:40
   |
27 |     NoJournal => libcryptsetup_rs_sys::CRYPT_ACTIVATE_NO_JOURNAL,
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_RECOVERY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:28:39
   |
28 |     Recovery => libcryptsetup_rs_sys::CRYPT_ACTIVATE_RECOVERY,
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_IGNORE_PERSISTENT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:29:47
   |
29 |     IgnorePersistent => libcryptsetup_rs_sys::CRYPT_ACTIVATE_IGNORE_PERSISTENT,
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_CHECK_AT_MOST_ONCE` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:30:46
   |
30 |     CheckAtMostOnce => libcryptsetup_rs_sys::CRYPT_ACTIVATE_CHECK_AT_MOST_ONCE,
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_ALLOW_UNBOUND_KEY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:31:46
   |
31 |     AllowUnboundKey => libcryptsetup_rs_sys::CRYPT_ACTIVATE_ALLOW_UNBOUND_KEY,
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_RECALCULATE` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:32:42
   |
32 |     Recalculate => libcryptsetup_rs_sys::CRYPT_ACTIVATE_RECALCULATE,
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_REFRESH` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:33:38
   |
33 |     Refresh => libcryptsetup_rs_sys::CRYPT_ACTIVATE_REFRESH,
   |                                      ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_SERIALIZE_MEMORY_HARD_PBKDF` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:34:55
   |
34 |     SerializeMemoryHardPbkdf => libcryptsetup_rs_sys::CRYPT_ACTIVATE_SERIALIZE_MEMORY_HARD_PBKDF,
   |                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_ACTIVATE_NO_JOURNAL_BITMAP` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:35:46
   |
35 |     NoJournalBitmap => libcryptsetup_rs_sys::CRYPT_ACTIVATE_NO_JOURNAL_BITMAP
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_DEACTIVATE_DEFERRED` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:49:39
   |
49 |     Deferred => libcryptsetup_rs_sys::CRYPT_DEACTIVATE_DEFERRED,
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_DEACTIVATE_FORCE` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/activate.rs:50:36
   |
50 |     Force => libcryptsetup_rs_sys::CRYPT_DEACTIVATE_FORCE
   |                                    ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VERITY_NO_HEADER` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:23:39
   |
23 |     NoHeader => libcryptsetup_rs_sys::CRYPT_VERITY_NO_HEADER,
   |                                       ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VERITY_CHECK_HASH` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:24:40
   |
24 |     CheckHash => libcryptsetup_rs_sys::CRYPT_VERITY_CHECK_HASH,
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VERITY_CREATE_HASH` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:25:41
   |
25 |     CreateHash => libcryptsetup_rs_sys::CRYPT_VERITY_CREATE_HASH
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_TCRYPT_LEGACY_MODES` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:41:42
   |
41 |     LegacyModes => libcryptsetup_rs_sys::CRYPT_TCRYPT_LEGACY_MODES,
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_TCRYPT_HIDDEN_HEADER` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:42:43
   |
42 |     HiddenHeader => libcryptsetup_rs_sys::CRYPT_TCRYPT_HIDDEN_HEADER,
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_TCRYPT_BACKUP_HEADER` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:43:43
   |
43 |     BackupHeader => libcryptsetup_rs_sys::CRYPT_TCRYPT_BACKUP_HEADER,
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_TCRYPT_SYSTEM_HEADER` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:44:43
   |
44 |     SystemHeader => libcryptsetup_rs_sys::CRYPT_TCRYPT_SYSTEM_HEADER,
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_TCRYPT_VERA_MODES` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/format.rs:45:40
   |
45 |     VeraModes => libcryptsetup_rs_sys::CRYPT_TCRYPT_VERA_MODES
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_KEYFILE_STOP_EOL` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/keyfile.rs:26:38
   |
26 |     StopEol => libcryptsetup_rs_sys::CRYPT_KEYFILE_STOP_EOL
   |                                      ^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VOLUME_KEY_NO_SEGMENT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/keyslot.rs:21:40
   |
21 |     NoSegment => libcryptsetup_rs_sys::CRYPT_VOLUME_KEY_NO_SEGMENT,
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VOLUME_KEY_SET` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/keyslot.rs:22:34
   |
22 |     Set => libcryptsetup_rs_sys::CRYPT_VOLUME_KEY_SET,
   |                                  ^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_VOLUME_KEY_DIGEST_REUSE` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/keyslot.rs:23:42
   |
23 |     DigestReuse => libcryptsetup_rs_sys::CRYPT_VOLUME_KEY_DIGEST_REUSE
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REQUIREMENT_OFFLINE_REENCRYPT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_flags.rs:17:47
   |
17 |     OfflineReencrypt => libcryptsetup_rs_sys::CRYPT_REQUIREMENT_OFFLINE_REENCRYPT,
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REQUIREMENT_ONLINE_REENCRYPT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_flags.rs:18:46
   |
18 |     OnlineReencrypt => libcryptsetup_rs_sys::CRYPT_REQUIREMENT_ONLINE_REENCRYPT,
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REQUIREMENT_UNKNOWN` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_flags.rs:19:38
   |
19 |     Unknown => libcryptsetup_rs_sys::CRYPT_REQUIREMENT_UNKNOWN
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REENCRYPT_INITIALIZE_ONLY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_reencrypt.rs:51:45
   |
51 |     InitializeOnly => libcryptsetup_rs_sys::CRYPT_REENCRYPT_INITIALIZE_ONLY,
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REENCRYPT_MOVE_FIRST_SEGMENT` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_reencrypt.rs:52:47
   |
52 |     MoveFirstSegment => libcryptsetup_rs_sys::CRYPT_REENCRYPT_MOVE_FIRST_SEGMENT,
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REENCRYPT_RESUME_ONLY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_reencrypt.rs:53:41
   |
53 |     ResumeOnly => libcryptsetup_rs_sys::CRYPT_REENCRYPT_RESUME_ONLY,
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_REENCRYPT_RECOVERY` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/luks2_reencrypt.rs:54:39
   |
54 |     Recovery => libcryptsetup_rs_sys::CRYPT_REENCRYPT_RECOVERY
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_PBKDF_ITER_TIME_SET` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/settings.rs:70:42
   |
70 |     IterTimeSet => libcryptsetup_rs_sys::CRYPT_PBKDF_ITER_TIME_SET,
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_PBKDF_NO_BENCHMARK` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/settings.rs:71:42
   |
71 |     NoBenchmark => libcryptsetup_rs_sys::CRYPT_PBKDF_NO_BENCHMARK
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

error[E0425]: cannot find value `CRYPT_WIPE_NO_DIRECT_IO` in crate `libcryptsetup_rs_sys`
  --> /home/perobins/.cargo/registry/src/github.com-1ecc6299db9ec823/libcryptsetup-rs-0.5.0/src/wipe.rs:56:39
   |
56 |                 libcryptsetup_rs_sys::CRYPT_WIPE_NO_DIRECT_IO
   |                                       ^^^^^^^^^^^^^^^^^^^^^^^ not found in `libcryptsetup_rs_sys`

For more information about this error, try `rustc --explain E0425`.
````
